// <auto-generated />
namespace Radabite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AdiosLocations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdiosLocations));
        
        string IMigrationMetadata.Id
        {
            get { return "201402211933566_AdiosLocations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
